

export const FETCH_CHALLENGE_FAILED='FETCH_CHALLENGE_FAILED';

export const FETCH_ALL_CHALLENGES='FETCH_ALL_CHALLENGES';
export const FETCH_NEW_CHALLENGES='FETCH_NEW_CHALLENGES';
export const FETCH_INFORMATION='FETCH_INFORMATION';
export const FETCH_INFORMATION_FAILED='FETCH_INFORMATION_FAILED';
export const VERIFYPASSWORD='VERIFYPASSWORD';
export const VERIFYREPEAT='VERIFYREPEAT';
export const ADDUSERCHALLENGE='ADDUSERCHALLENGE';
export const ADDUSERNAME='ADDUSERNAME';
export const ADDALLUC='ADDALLUC';